server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.22.32:3306/hm_task?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hm.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
#    com.kumiko.dao: debug